# Generated by Django 5.1.1 on 2024-09-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DirectionOfStudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='myapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_of_start_of_work', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='myapp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='myapp.directionofstudy')),
                ('curator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='myapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='myapp.directionofstudy')),
                ('lecture_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_disciplines', to='myapp.teacher')),
                ('practice_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_disciplines', to='myapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to='myapp.teacher'),
        ),
        migrations.CreateModel(
            name='UserToGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='headmen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headman', to='myapp.usertogroup'),
        ),
    ]
